# 1. Imagem base
FROM python:3.11-slim

# 2. Configurações de ambiente para o Python não criar arquivos .pyc e exibir logs na hora
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 3. Define a pasta de trabalho dentro do container
WORKDIR /app

# 4. Instala dependências do sistema (necessárias para o driver do Postgres)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# 5. Copia e instala as dependências do Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copia o restante do código para o container
COPY . .

# 7. Comando para rodar a aplicação
# Importante: host 0.0.0.0 permite acesso externo ao container
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]